# Generated by Django 4.2.1 on 2023-05-07 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_train',
            name='distance',
        ),
    ]
