# Generated by Django 4.2.1 on 2023-05-23 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_remove_add_train_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='aadhar',
            field=models.CharField(max_length=12, null=True, verbose_name='aadhar'),
        ),
        migrations.AddField(
            model_name='register',
            name='confirmpasswd',
            field=models.CharField(max_length=10, null=True, verbose_name='Confirm password'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='date1',
            field=models.DateField(default=datetime.date(2023, 5, 23)),
        ),
    ]
