# Generated by Django 4.2.1 on 2023-05-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_alter_passenger_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='message',
        ),
    ]
