# Generated by Django 4.2.1 on 2023-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_remove_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
