# Generated by Django 4.2.1 on 2023-05-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_contactmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_shedulde',
            name='remaining_seats',
            field=models.IntegerField(default=0),
        ),
    ]
