# Generated by Django 4.2.1 on 2023-05-24 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_train_shedulde_remaining_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('date1', models.DateField(default=datetime.date(2023, 5, 24))),
                ('fare', models.IntegerField(null=True)),
                ('seat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.seat')),
                ('train', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.add_train')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.register')),
            ],
        ),
    ]
