# Generated by Django 4.2.1 on 2023-05-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0008_book_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='cancel_request',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
    ]
