# Generated by Django 4.2.1 on 2023-05-25 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_passenger_cancel_request_alter_register_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirmpasswd',
        ),
        migrations.AlterField(
            model_name='book_details',
            name='date1',
            field=models.DateField(default=datetime.date(2023, 5, 25)),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='date1',
            field=models.DateField(default=datetime.date(2023, 5, 25)),
        ),
        migrations.AlterField(
            model_name='register',
            name='aadhar',
            field=models.CharField(max_length=15, null=True, verbose_name='aadhar'),
        ),
    ]
